#!/usr/bin/python

import sys
from optparse import OptionParser

parser = OptionParser()
parser.add_option("-i", "--input-file", dest="input", help="Input file (default stdin)")
parser.add_option("-o", "--output-file", dest="output", help="Output file (default stdout)")
parser.add_option("-n", "--array-name", dest="name", help="Name of array", default="some_array")
(options, args) = parser.parse_args()

#
# warning: no check for arguments, just assume the caller
# is sane

if options.input:
	ifile = file(options.input, "r")
else:
	ifile = sys.stdin

if options.output:
	ofile = file(options.output, "w")
else:
	ofile = sys.stdout

bytes = ifile.read()
ofile.write("/*\n * Autogenerated file, do not edit\n */\n")
ofile.write("unsigned char %s[] = {" % options.name)
ofile.write(", ".join([hex(ord(c)) for c in bytes]))
ofile.write("};\n")
ofile.write("unsigned int %s_size = sizeof(%s);" % (options.name, options.name))
