#ifndef KVM__KVM_ARCH_H
#define KVM__KVM_ARCH_H

#include <linux/const.h>

#define ARM_LOMAP_MMIO_AREA	_AC(0x00000000, UL)
#define ARM_LOMAP_AXI_AREA	_AC(0x40000000, UL)
#define ARM_LOMAP_MEMORY_AREA	_AC(0x80000000, UL)
#define ARM_LOMAP_MAX_MEMORY	_AC(0x7fffffff, UL)

#define ARM_GIC_DIST_SIZE	0x1000
#define ARM_GIC_DIST_BASE	(ARM_LOMAP_AXI_AREA - ARM_GIC_DIST_SIZE)
#define ARM_GIC_CPUI_SIZE	0x2000
#define ARM_GIC_CPUI_BASE	(ARM_GIC_DIST_BASE - ARM_GIC_CPUI_SIZE)

#define ARM_KERN_OFFSET		0x8000

#define ARM_SMP_PEN_SIZE	PAGE_SIZE
#define ARM_VIRTIO_MMIO_SIZE	(ARM_GIC_DIST_BASE - ARM_LOMAP_MMIO_AREA)
#define ARM_PCI_MMIO_SIZE	(ARM_LOMAP_MEMORY_AREA - ARM_LOMAP_AXI_AREA)

#define ARM_MEMORY_AREA		ARM_LOMAP_MEMORY_AREA
#define ARM_MAX_MEMORY		ARM_LOMAP_MAX_MEMORY

#define KVM_PCI_MMIO_AREA	ARM_LOMAP_AXI_AREA
#define KVM_VIRTIO_MMIO_AREA	ARM_LOMAP_MMIO_AREA

#include "arm-common/kvm-arch.h"

#endif /* KVM__KVM_ARCH_H */
